### ISSUE TITLE
Make search by user/project case insensitive

### ISSUE THREAD

**Issue by C-Entropy** [ultralisp/ultralisp#105]
Right now search results contains a link https://ultralisp.org/projects/shinmera/tooter

Yes, it give 404 sometime and Internal Server Error other time.

Ultralisp is not able to find it because user name is `Shinmera` in the database.

**Comment by svetlyak40wt** [comment]
Interesting, I need to check it.

**Comment by svetlyak40wt** [comment]
@C-Entropy where did you find this link?

**Comment by C-Entropy** [comment]
Just search audio-tag

**Comment by svetlyak40wt** [comment]
Oh, seems, Ultralisp searches the name as "shinmera", but in the database it is "Shinmera".

Here is the correct link: https://ultralisp.org/projects/Shinmera/tooter

I think, we need to make this search case insensitive.

**Comment by C-Entropy** [comment]
Looks like this.
