### ISSUE TITLE
Organization account project not displayed/downloadable in personal dist

### ISSUE THREAD

**Issue by digikar99** [ultralisp/ultralisp#130]
I added `lisp-maintainers/cl-syntax` to the custom dist [digikar99/specialized-array-dispatch](https://ultralisp.org/dists/digikar99/specialized-array-dispatch), but:

```lisp
CL-USER> (ql-dist:provided-releases (ql-dist:find-dist  "digikar99/specialized-array-dispatch"))
(#<QL-DIST:RELEASE digikar99-trivial-types-20210421175237 / digikar99/specialized-array-dispatch 20210421212500>
 #<QL-DIST:RELEASE digikar99-abstract-arrays-20210421174952 / digikar99/specialized-array-dispatch 20210421212500>
 #<QL-DIST:RELEASE digikar99-adhoc-polymorphic-functions-20210421174854 / digikar99/specialized-array-dispatch 20210421212500>
 #<QL-DIST:RELEASE digikar99-trivial-coerce-20210421175203 / digikar99/specialized-array-dispatch 20210421212500>
 #<QL-DIST:RELEASE digikar99-trivial-form-type-20210421175110 / digikar99/specialized-array-dispatch 20210421212500>
 #<QL-DIST:RELEASE digikar99-dense-arrays-20210421175010 / digikar99/specialized-array-dispatch 20210421212500>)
;;; Also another attempt of removing and readding:
(#<QL-DIST:RELEASE digikar99-dense-arrays-20210421175010 / digikar99/specialized-array-dispatch 20210421213000>
 #<QL-DIST:RELEASE digikar99-trivial-types-20210421175237 / digikar99/specialized-array-dispatch 20210421213000>
 #<QL-DIST:RELEASE digikar99-abstract-arrays-20210421174952 / digikar99/specialized-array-dispatch 20210421213000>
 #<QL-DIST:RELEASE digikar99-adhoc-polymorphic-functions-20210421174854 / digikar99/specialized-array-dispatch 20210421213000>
 #<QL-DIST:RELEASE digikar99-trivial-coerce-20210421175203 / digikar99/specialized-array-dispatch 20210421213000>
 #<QL-DIST:RELEASE digikar99-trivial-form-type-20210421175110 / digikar99/specialized-array-dispatch 20210421213000>)
```

While I can see the projects from my own repositories, I cannot see the project `lisp-maintainers/cl-syntax`, even though I do have admin access to the organization `lisp-maintainers`. Is this a bug or is there some other way to achieve this?

**Comment by digikar99** [comment]
Okay, I had to approve access to Ultralisp.org from lisp-maintainers: https://docs.github.com/en/organizations/restricting-access-to-your-organizations-data/approving-oauth-apps-for-your-organization

**Comment by svetlyak40wt** [comment]
By the way, @digikar99, Quicklisp client does not support Ultralisp's custom distribution now, because @xach [reverted](https://github.com/quicklisp/quicklisp-client/commit/4727689c6fcde89149a8a6c5496662cde939a727) my [pull](https://github.com/quicklisp/quicklisp-client/pull/206) which allowed project names with `/` symbol :(

**Comment by digikar99** [comment]
Oh yes, but for my purposes, pushing a custom function to `ql::*dist-enumeration-functions*` works. A more elaborate explanation [here](https://github.com/digikar99/adhoc-polymorphic-functions#getting-it-from-ultralisp). In fact, for the time being, one could also add those (the ones in the PR) functions to one's init file and push `find-distinfo-files` to `ql::*dist-enumeration-functions*`. The issue with that would be new lisp users requiring yet another configuration step. 

I agree this needs a better fix in the longer run, but also that the quicklisp dist itself needs more immediate attention due to a fair number of [pending issues](https://github.com/quicklisp/quicklisp-projects/issues?page=1&q=is%3Aissue+is%3Aopen) new and old, some seem to be actually resolved but are still open, and/or a more scaleable way out. Almost equally important I think is moving to https.

**Comment by svetlyak40wt** [comment]
Oh, probably the easiest way will be to create "ultralisp-client" system, which will provide a `ul:quickload` function and do a proper `ql::*dist-enumeration-functions*` binding?

**Comment by digikar99** [comment]
For purposes of custom dists, providing a separate client method doesn't seem significantly easier than just manually adding code to init file. 

But, I can imagine an `ultralisp-client` system in quicklisp dist itself, which also provides a function to install the `ultralisp` dist itself. So, in order to use ultralisp dist, instead of the current visit-to-website* -> copy-paste-run-code, one could `(ql:quickload "ultralisp-client")` and `(ul:install-ultralisp-dist)` or `(ul:install-dist "my/custom-dist")` or some combination thereof. 

*And while this isn't too much an issue, opening ultralisp.org and copy-pasting the code feels simpler than recalling a few things: if it's ql or ql-dist, if it's http or https, if it's just ultralisp or something before it.
