### ISSUE TITLE
"No asd files were found!" error on the renamed project page, after a project was renamed on github

### ISSUE THREAD

**Issue by digikar99** [ultralisp/ultralisp#132]
I renamed a project from adhoc-polymorphic-functions to polymorphic-functions on github. Few issues:

1. I added the new project polymorphic-functions, however an error prevents it from being added: https://ultralisp.org/projects/digikar99/polymorphic-functions

```
Traceback (most recent call last):
   0 File "/app/src/utils.lisp", line 198
       In ULTRALISP/UTILS:GET-TRACEBACK
     Args (#<SIMPLE-ERROR "No asd files were found!" {100B53ABB3}>)
   1 File "/app/src/pipeline/checking.lisp"
       In (FLET "H0" :IN ULTRALISP/PIPELINE/CHECKING::PERFORM2)
     Args (#<SIMPLE-ERROR "No asd files were found!" {100B53ABB3}>)
   2 File "unknown"
       In SB-KERNEL::%SIGNAL
     Args (#<SIMPLE-ERROR "No asd files were found!" {100B53ABB3}>)
   3 File "unknown"
       In ERROR
     Args ("No asd files were found!")
   4 File "/app/src/pipeline/checking.lisp", line 332
       In ULTRALISP/PIPELINE/CHECKING::PERFORM2
     Args (#<ULTRALISP/MODELS/CHECK:CHECK2 PENDING MANUAL for #<SOURCE github://digikar99/polymorphic-functions@NIL (v1)>> :FORCE NIL)
   5 File "/app/src/rpc/command.lisp", line 76
       In TASK-WITH-COMMANDS
     Args ("172.17.0.1" "ultralisp_ro" #<secret value> "ultralisp" ULTRALISP/PIPELINE/CHECKING::PERFORM2 #<ULTRALISP/MODELS/CHECK:CHECK2 PENDING MANUAL for #<SOURCE github://digikar99/polymorphic-functions@NIL (v1)>>)
   6 File "/app/src/worker.lisp"
       In (LAMBDA (ARG JOB) :IN PROCESS-JOBS)
     Args (#<hidden arg> #<hidden arg>)
   7 File "/app/.qlot/dists/cl-gearman/software/cl-gearman-patches/src/worker.lisp"
       In (:METHOD CL-GEARMAN::RUN-JOB (CL-GEARMAN:WORKER CL-GEARMAN::JOB))
     Args (#<CL-GEARMAN:WORKER {100738E403}> #<hidden arg>)
   8 File "/app/src/worker.lisp", line 56
       In PROCESS-JOBS
     Args (:ONE-TASK-ONLY T)
   9 File "/app/src/worker.lisp", line 81
       In MAIN
     Args ("--one-task-only" "--slynk-interface" "0.0.0.0" "--slynk-port" "4005" "--debug")
```

2. I tried to remove the old project https://ultralisp.org/projects/digikar99/adhoc-polymorphic-functions by clicking on the red "Remove" button that appears there, but I can still see it on [my dist](https://ultralisp.org/dists/digikar99/specialized-array-dispatch); is there some other way to remove it?

**Comment by svetlyak40wt** [comment]
Well, this traceback says the problem is "No asd files were found." And I don't see any asd files in the https://github.com/digikar99/polymorphic-functions repository.

From Ultralisp's point of view, this repository does not contain an ASDF system. Thus it can't be added.

**Comment by digikar99** [comment]
Oops, my bad!

**Comment by svetlyak40wt** [comment]
On "removing" problem. Removing is not very well tested. This seems a bug. I've created an issue:
https://github.com/ultralisp/ultralisp/issues/133

But this bug shouldn't break the distribution. I think it is only in the web representation.
