### ISSUE TITLE
Unable to build docker container

### ISSUE THREAD

**Issue by nmunro** [ultralisp/ultralisp#145]
I'm using macos 11.5.2, but running `docker-compose up app` (as per https://github.com/ultralisp/ultralisp#easy-way) or `make all` (as per https://github.com/ultralisp/ultralisp#harder-way) doesn't work.

I have attached the build output (gathered via script), if there's anything I can do to help, let me know.

[typescript.txt](https://github.com/ultralisp/ultralisp/files/7180370/typescript.txt)

**Comment by svetlyak40wt** [comment]
Makefile is outdated. I'm using `Lakefile` instead. But `docker-compose up app` should work.

Looking at the error in your log, I can say that problem is in the building `skarnet`. It is used inside the docker container an init process. Seems, I don't have such problems because this command is cached on my computer.

I'll try to redo building while dropping cache tomorrow.

**Comment by svetlyak40wt** [comment]
I was able to reproduce this issue on a clean virtual machine. Will try to solve it asap.

By the way, @nmunro why did you decide to try how to set up Ultralisp for development?

**Comment by nmunro** [comment]
I think we spoke on twitter a little while ago about helping out, and I have some vacation days coming up so I thought I'd see if there was anything I _could_ help with and hit this trying to get it up and running.

**Comment by svetlyak40wt** [comment]
Aha! Cool! I'll let you know when solve this issue!

**Comment by svetlyak40wt** [comment]
Fixed issue in commit https://github.com/ultralisp/ultralisp/commit/a63b1b226423b8044460d6e44e1f0a0afc1e6ac5 now everything builds and starts.

**Comment by svetlyak40wt** [comment]
@nmunro also, see this commit I've just added: https://github.com/ultralisp/ultralisp/commit/490f1a556fed8b8cf9077d961e9bb04bca14964b#diff-7b3ed02bc73dc06b7db906cf97aa91dec2b2eb21f2d92bc5caa761df5bbc168fR77 it fixes database name and shows how to run db migrations before app. Without migrations, postgres database will be absent and app will not start.
