### ISSUE TITLE
It seems Ultralisp stopped updating

### ISSUE THREAD

**Issue by shamazmazum** [ultralisp/ultralisp#151]
Hi! It seems there is something wrong with updating again. E.g. [imago](https://ultralisp.org/projects/tokenrove/imago) is number 1073 in the queue for hours. Can you check, please?

**Comment by svetlyak40wt** [comment]
Yes. Some shit happened. Restarted the server and now it slowly processes updates.

**Comment by shamazmazum** [comment]
Thanks!
