### ISSUE TITLE
Behaviour when entry in UL provides same system

### ISSUE THREAD

**Issue by Zulu-Inuoe** [ultralisp/ultralisp#195]
Hey all,

[@fosskers](https://github.com/fosskers) encountered odd behaviour in trying to load jzon from Ultralisp:

```lisp
CL-USER> (ql:quickload :com.inuoe.jzon )
To load "com.inuoe.jzon":
  Load 3 ASDF systems:
    closer-mop flexi-streams uiop
  Install 1 Quicklisp release:
    MarceColl-isen
; Loading "com.inuoe.jzon"
[package com.inuoe.jzon].........
(:COM.INUOE.JZON)
```

We tracked it down to the fact that this project: <https://ultralisp.org/projects/MarceColl/isen> includes an old vendored version of jzon.
I am assuming this is happening because UL just sees that there is a `com.inuoe.jzon.asd` in that project and thinks it's the provider.

I don't know what -should- happen here but has anyone run into this sort of thing before? It seems like a foot gun if somebody happens to vendor some other library in their repo that gets added to UL

Thanks

**Comment by svetlyak40wt** [comment]
I've added `jzon/` folder to ignore list for `isen`:

<img width="776" alt="Screen Shot 2023-02-24 at 12 18 17" src="https://user-images.githubusercontent.com/24827/221140381-f81dd288-2375-4b65-9bc4-4afb8bd2d123.png">

and in newest build of the Ultralisp dist the problem should disappear.

**Comment by svetlyak40wt** [comment]
Thank you for the report!

**Comment by fstamour** [comment]
Related to #73

**Comment by fstamour** [comment]
Similar to #127 and #70

**Comment by Zulu-Inuoe** [comment]
@svetlyak40wt  Thank you for looking at that so quickly! Out of curiosity, Is the ignored directories something users have control over when adding to UL, or is it something we poke an admin for?

Thanks

BTW related to - https://github.com/ultralisp/ultralisp/issues/195

**Comment by svetlyak40wt** [comment]
Admin can edit any project in Ultralisp, but users should be able to set this ignore list for their projects too.

The list of projects you own is here: https://ultralisp.org/my/projects
