### ISSUE TITLE
Question: Using Ultralisp with Lem Extensions: Labeling and API Queries

### ISSUE THREAD

**Issue by cxxxr** [ultralisp/ultralisp#205]
Hi, I am very grateful for the wonderful project you are working on.

I have a few questions, as I may not fully understand this project yet.

I am considering using Ultralisp as a package manager for Lem extensions.

Would it be possible to do the following with Ultralisp?
- Add labels to repositories for Lem extensions and filter them
- Have an API to retrieve repositories registered with Ultralisp

I'd appreciate your help.

**Comment by svetlyak40wt** [comment]
Sure! I've already added labeling. Here it is in action:

![ultralisp-tags](https://github.com/ultralisp/ultralisp/assets/24827/7bdb1dc7-4d47-456f-a5fc-231fbca4c33f)

**Comment by cxxxr** [comment]
Very nice!
I would love to use the functions when it is added.

**Comment by seanfarley** [comment]
Would it be possible to leave this issue open until the API is finished and usuable with OpenRPC?

**Comment by svetlyak40wt** [comment]
Here is a main issue which can be tracked: https://github.com/ultralisp/ultralisp/issues/212

**Comment by seanfarley** [comment]
Thanks!

**Comment by svetlyak40wt** [comment]
@seanfarley @cxxxr The first version of API and [lisp client](https://ultralisp.github.io/ultralisp-client/) were implemented!

**Comment by seanfarley** [comment]
<dance party>

**Comment by cxxxr** [comment]
Thank you so much!
I would like to start working on the introduction of ultralisp to lem.
