### ISSUE TITLE
Question about Authorize when logging in with OAuth

### ISSUE THREAD

**Issue by cxxxr** [ultralisp/ultralisp#206]
![Screenshot from 2023-06-15 21-35-26](https://github.com/ultralisp/ultralisp/assets/13656378/778b7952-8afa-4e45-8ccd-156e309b9410)

Related issue: https://github.com/ultralisp/ultralisp/issues/39

I attempted to log into Ultralisp, but I was a bit afraid when I saw the required permissions.
Is it necessary to have permissions to read private projects and admin access to webhooks?
Or if there is another means of registering the repository, please let us know.

I apologize if I've said anything wrong due to my lack of understanding.

Best regards.

**Comment by svetlyak40wt** [comment]
These permissions should not be required to just logging in.

When you just log in, only permission to read email is requested:

<img width="583" alt="login-permissions" src="https://github.com/ultralisp/ultralisp/assets/24827/eb3376e7-93b5-4f8d-b21a-c174582e63f0">

Then, to add a project, you hit this button:

<img width="682" alt="add-projects-button" src="https://github.com/ultralisp/ultralisp/assets/24827/2596239d-dcae-424b-9b99-c00d4d763315">

After that, you have two ways how to add a project:

<img width="1014" alt="two-ways-of-adding-projects" src="https://github.com/ultralisp/ultralisp/assets/24827/ce4fb967-c0cd-4ac0-89f1-017842c67599">

## Way 1

Hit the "Grant permission" button and Ultralisp will request additional permissions which let to read repository listings and to setup webhooks:

<img width="525" alt="add-project-permissions" src="https://github.com/ultralisp/ultralisp/assets/24827/152a1093-ac7d-415d-86c8-4a8647478ba6">


Then Ultralisp will fetch all lisp repositories from all public repositories your organizations and present them on a page like this:

<img width="982" alt="github-projects-list" src="https://github.com/ultralisp/ultralisp/assets/24827/878040a8-7763-465e-b678-b939f8e805a3">

All you need now is to turn on switchers on projects you'd like to add to Ultralisp.

With this approach, Ultralisp will setup a commit hook for each added repository and will build a new release as soon as you push a new commit.

## Way 2

Don't grant permissions, just paste github URL into the form and press "Add" button. The project will be added but without a hook. It will be checked only from time-to time by a cron. Time intervals depends on commit frequency. Higher commit frequency – lower checks interval. Maximum checking interval is two weeks.

**Comment by svetlyak40wt** [comment]
Probably it is time to add a built in documentation and some articles explaining how everything work.

**Comment by cxxxr** [comment]
Thank you for the very detailed explanation.
I will do some digging.

The documentation may indeed be helpful to have.

**Comment by svetlyak40wt** [comment]
I forgot to say, that with the second way (pasting the URL), you can add to Ultralisp not only you own repositories, but any GitHub repository, which can be convenient when you found an interesting code which is not in the Quicklisp yet.

**Comment by cxxxr** [comment]
Thank you so much!
