### ISSUE TITLE
Supporting generic Git repositories

### ISSUE THREAD

**Issue by fosskers** [ultralisp/ultralisp#210]
If a project moves to a different source forge, how can Ultralisp be informed of this?

See also #209 , in case that's related.

**Comment by fosskers** [comment]
I've moved one of my projects (`transducers`) to SourceHut. Is Ultralisp doing more than just a `git clone --shallow` when building packages? Is it specifically using Github's API in some way that prevents other forges from being used?

**Comment by svetlyak40wt** [comment]
Ultralisp uses GitHub API to set a hook to rebuild distribution an every commit to the master branch. Also, it uses API to fetch all branches when you are editing the project's source.

Generic Git repositories could be supported as well, but I still can't find time to implement this type of source :(

If you would like to help with this task I'll be happy!

**Comment by svetlyak40wt** [comment]
Ultralisp can work without a hook. This happens when you just post a repository's URL without given an access the the GitHub repository. In this case Ultralisp will check repository periodically. However in this case check period might be up to a week. More frequently updated projects are checked more frequently.

Also there is a "Check" button on the project page (if you are a maintainer of this project). It adds project to the queue for check.

I'm planning to add a JSON-RPC API to Ultralisp (for searching the projects). And a method for forcing the check could be added as well. Most probably, API will be added in the first part of August.

**Comment by fosskers** [comment]
> I'm planning to add a JSON-RPC API to Ultralisp (for searching the projects). And a method for forcing the check could be added as well.

That should be enough! Then as long as I had some auth secret in the CI of my project (on SourceHut), I can call the JSON endpoint manually.

Okay, for now can we keep this issue open, and then I can help you test once you've made those additions?

**Comment by svetlyak40wt** [comment]
Also it would be good to solve this issue https://github.com/ultralisp/ultralisp/issues/211 because otherwise you'll require to have a GitHub profile to add repostories from SourceHut.

**Comment by svetlyak40wt** [comment]
Created an issue about API: https://github.com/ultralisp/ultralisp/issues/212 it will be required for supporting push scenario.

**Comment by fosskers** [comment]
Thank you very much!

**Comment by fosskers** [comment]
I just noticed that McClim has similar moved off of Github and continued their development on [Codeberg](https://codeberg.org/McCLIM/McCLIM), but Ultralisp is still on their last Github commit from March.

**Comment by svetlyak40wt** [comment]
Congratulations! Ultralisp now supports any git repositories! I've already switched your repository: https://ultralisp.org/projects/fosskers/cl-transducers

Here is a short instruction how to do such migration:

![ultralisp-move-from-github](https://github.com/ultralisp/ultralisp/assets/24827/378371a0-7f32-41d3-b739-30e0c47811a1)

**Comment by fosskers** [comment]
Holy crap that's amazing! Thank you!

**Comment by fosskers** [comment]
I logged in and confirmed that I could indeed alter the settings myself. Thanks again!
