### ISSUE TITLE
Add a JSON RPC API to retrieve data from Ultralisp

### ISSUE THREAD

**Issue by svetlyak40wt** [ultralisp/ultralisp#212]
I'm planning to create an API to work with Ultralisp. This way we'll be able to retrieve projects hosted on Ultralisp and filter them by tags. This required for using Ultralisp as a registry for Lem or NYXT plugins (https://github.com/ultralisp/ultralisp/issues/35).

I'm planning to use https://40ants.com/openrpc/ for adding an API.

Also, there was an idea to add a method for forcing the check of the project. But this will require some kind of authentication in API. Probably I'll have to support personal API tokens and will need to create an interface to issue these tokens and db table to store their hashes.

**Comment by svetlyak40wt** [comment]
The first version of API and [lisp client](https://ultralisp.github.io/ultralisp-client/) were implemented!

**Comment by seanfarley** [comment]
Amazing!
