### ISSUE TITLE
Unable to add a new non-Github project?

### ISSUE THREAD

**Issue by fosskers** [ultralisp/ultralisp#216]
Hi again and thank you very much for the recent upgrades!

I tried to add a new project to Ultralisp via the new URL feature last night (and again this morning), but am told:

![ultralisp-internal-error](https://github.com/ultralisp/ultralisp/assets/229679/927f3d84-cb8f-4bfe-af14-7e2b000275be)

Do you know what might be happening here? Thank you!

**Comment by svetlyak40wt** [comment]
Could you please check if this bug is reproducible?

Today my server experienced some strange networking issues. They are caused timeouts and probably have affected you as well.

**Comment by fosskers** [comment]
Yes it's still happening.

**Comment by svetlyak40wt** [comment]
This issue should be fixed now.

**Comment by fosskers** [comment]
Yup, thank you!
