### ISSUE TITLE
Loading named-readtables failed

### ISSUE THREAD

**Issue by fukamachi** [ultralisp/ultralisp#228]
Loading the latest named-readtables from Ultralisp failed because of [the recent commit](https://github.com/melisgl/named-readtables/commit/7a60d455c1ac8a3fc25890307f421a87133482ff) to it.

"mgl-pax/bootstrap" was renamed to "mgl-pax-bootstrap", but it's not updated in Ultralisp. Failure log is here: https://ultralisp.org/projects/melisgl/mgl-pax.

**Comment by svetlyak40wt** [comment]
I'll try to fix it ASAP.

**Comment by svetlyak40wt** [comment]
Done. Named-readtables is loadable from the latest dist release.

**Comment by svetlyak40wt** [comment]
Thanks for paying attention to the service!

**Comment by fukamachi** [comment]
Wow, thank you for the quick fix!
