### ISSUE TITLE
Add a fuzzy search among all symbols in all systems

### ISSUE THREAD

**Issue by svetlyak40wt** [ultralisp/ultralisp#23]
We need to create a task, which will load the system, extract all external symbols (and their documentation) and put into the Postgres. Afterwards, it should add these symbols into the search index.

Probably, we'll need to use a [Montezuma](http://quickdocs.org/montezuma/) or a separate Elastic Search server.

Also, a search bar should be created. When a user is typing, it should show a fuzzy autocomplete and when he selects an item from the dropdown, we should show a separate page with information about the symbol.

**This will be useful if you want a utility function, something like `url-escape` and see if it is already implemented in some libraries.**

There is also another task about fuzzy search: https://github.com/ultralisp/ultralisp/issues/36

**Comment by vindarel** [comment]
Did you consider Postgres' full-text search alone ?

**Comment by svetlyak40wt** [comment]
If it is able to do a fuzzy search, why not!

**Comment by svetlyak40wt** [comment]
Ideally, the search should return indices of substrings which matched to the query like this Helm in Emacs:

![2019-02-10_20-18-43](https://user-images.githubusercontent.com/24827/52536877-1fd33300-2d71-11e9-91ac-4c1825a93f9e.png)

**Comment by egao1980** [comment]
On PG fuzz search => http://rachbelaid.com/postgres-full-text-search-is-good-enough/
