### ISSUE TITLE
Sly cannot connect

### ISSUE THREAD

**Issue by veer66** [ultralisp/ultralisp#239]
1. I ran lake devserver as shown in the top-left buffer
2. Docker compose could create containers as shown in the top-right buffer.
3. I checked the web via http://172.19.0.6. It worked.
4. I ran sly-connect at 127.0.0.1 port 14005 as written in README. It didn't work.

https://github.com/ultralisp/ultralisp/assets/370688/8c43c088-60d6-4d72-8dc1-ae9b57595d37

**Comment by veer66** [comment]
I ran everything on my laptop without any cloud or vm.

**Comment by svetlyak40wt** [comment]
Did you try to replace 127.0.0.1 with 172.19.0.6 when connecting to SLY?

Also, show output of these probes:

```
telnet 127.0.0.1 14005
telnet 127.0.0.1 8080
```

and

```
telnet 172.19.0.6 14005
telnet 172.19.0.6 8080
```

**Comment by veer66** [comment]
> Did you try to replace 127.0.0.1 with 172.19.0.6 when connecting to SLY?

No, I didn't
 
> Also, show output of these probes:
> 
> ```
> telnet 127.0.0.1 14005
> telnet 127.0.0.1 8080
> ```
> 
> and
> 
> ```
> telnet 172.19.0.6 14005
> telnet 172.19.0.6 8080
> ```

By running lake devserver again today, I got this:

```
veer66@vextensa:~/Develop/free/lisp/ultralisp$ telnet 127.0.0.1 14005
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
Connection closed by foreign host.


veer66@vextensa:~/Develop/free/lisp/ultralisp$ telnet 127.0.0.1 8080
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.

HTTP/1.0 400 Bad Request
Connection: close

Your request could not be interpreted by this HTTP server

Connection closed by foreign host.




veer66@vextensa:~/Develop/free/lisp/ultralisp$ telnet 172.19.0.3 14005
Trying 172.19.0.3...
telnet: Unable to connect to remote host: Connection refused

veer66@vextensa:~/Develop/free/lisp/ultralisp$ telnet 172.19.0.3 8080
Trying 172.19.0.3...
telnet: Unable to connect to remote host: Connection refused
veer66@vextensa:~/Develop/free/lisp/ultralisp$ 
```

I also ran docker inspect ultralisp_app. The network setting looked like this:


```JSON
{
  "Bridge": "",
  "HairpinMode": false,
  "LinkLocalIPv6Address": "",
  "LinkLocalIPv6PrefixLen": 0,
  "Ports": {
    "4005/tcp": [
      {
        "HostIp": "127.0.0.1",
        "HostPort": "14005"
      }
    ],
    "80/tcp": [
      {
        "HostIp": "127.0.0.1",
        "HostPort": "8080"
      }
    ]
  },
  "SecondaryIPAddresses": null,
  "SecondaryIPv6Addresses": null,
  "EndpointID": "",
  "Gateway": "",
  "GlobalIPv6Address": "",
  "GlobalIPv6PrefixLen": 0,
  "IPAddress": "",
  "IPPrefixLen": 0,
  "IPv6Gateway": "",
  "Networks": {
    "ultralisp_default": {
      "IPAMConfig": null,
      "Links": null,
      "Aliases": [
        "ultralisp_app",
        "app",
        "824e3827dca4"
      ],
      "Gateway": "172.19.0.1",
      "IPAddress": "172.19.0.3",
      "IPPrefixLen": 16,
      "IPv6Gateway": "",
      "GlobalIPv6Address": "",
      "GlobalIPv6PrefixLen": 0,
      "DriverOpts": null
    }
  }
}
```

(I remove mac addresses from the JSON above.)

**Comment by svetlyak40wt** [comment]
Ok, try to check if SLYNK is running inside the ultralisp_app container. Do something like this:

```
docker exec -ti ultralisp_app bash
# then inside the container
apt install nettools
netstat -nlpt | grep 4005
```

**Comment by veer66** [comment]
> Ok, try to check if SLYNK is running inside the ultralisp_app container. Do something like this:
> 
> ```
> docker exec -ti ultralisp_app bash
> # then inside the container
> apt install nettools
> netstat -nlpt | grep 4005
> ```

No, nothing is running at the port 4005.

```
# netstat -nlpt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.11:42199        0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      12/ultralisp-server 
```

**Comment by svetlyak40wt** [comment]
Oh, I've found the reason. Probably some env vars where lost when we refactored docker compose files.

I've fixed this in the commit: https://github.com/ultralisp/ultralisp/commit/fa58f76f7c33b0fcb5b091ef90760ef59b8111ca

Pull this commit from the master.

**Comment by veer66** [comment]
It works now.

![image](https://github.com/ultralisp/ultralisp/assets/370688/3118f731-43a8-4e9a-9f4a-426ebb3cc3e6)
