### ISSUE TITLE
Create a script which will import projects from the Quicklisp

### ISSUE THREAD

**Issue by svetlyak40wt** [ultralisp/ultralisp#24]
It should take data from [this repository](https://github.com/quicklisp/quicklisp-projects/tree/master/projects)  walk over all subdirectories, and check if the project's source type is supported by Ultralisp. If supported, it should add a project if it does not already exists in the database.

It first stage, script should be able to import all projects,  hosted on the github.

At the end, script should output a list of unsupported source types, count of projects in Quicklisp, using them and a few examples of projects from which use these source types. This will help to decide which source to implement next in the Ultralisp.

**Comment by ryukinix** [comment]
Interesting task!

**Comment by svetlyak40wt** [comment]
It is almost done. It required to change a architecture of the project, to handle large amount of projects and to not rebuild every project for every version increment.

I hope to release a new Ultralisp on next weekend.

**Comment by ryukinix** [comment]
Great news! Exciting. I'll share this with my CL colleagues

**Comment by Hexstream** [comment]
Congratulations on 1000+ imported projects! :rocket:
