### ISSUE TITLE
Stuck on check wait queue

### ISSUE THREAD

**Issue by Hectarea1996** [ultralisp/ultralisp#241]
I'm trying to upload my project but it got stuck in the check waiting list for days. I can't see if my project is throwing any errors, so I don't know if it is my fault. See the creation date in the following image. Also, the queue position is not changing.

![clith](https://github.com/ultralisp/ultralisp/assets/17879146/59d2e76b-cd86-46c4-bf7e-66a4379dfbfa)

**Comment by svetlyak40wt** [comment]
That is interesting. I need some time to investigate why does it stuck.

**Comment by svetlyak40wt** [comment]
I found the problem and fixed it in the https://github.com/ultralisp/ultralisp/pull/242

The state of the database is already fixed and check was performed.

**Comment by Hectarea1996** [comment]
Thank you!!
