### ISSUE TITLE
My project not updating on UltraLisp

### ISSUE THREAD

**Issue by rabbibotton** [ultralisp/ultralisp#246]
I took a look at my project it is not getting updated (rabbibotton/clog) why?

It has not updated in over a year yet there have been commits and releases.

**Comment by svetlyak40wt** [comment]
You can click on this "error" link, to see the reason, why the last project check was failed:

<img width="965" alt="Screenshot 2024-02-02 at 12 26 52" src="https://github.com/ultralisp/ultralisp/assets/24827/a6d831bb-8313-4f24-a6f8-63dc43a70d10">

In your case backtrace says it have some problem compiling mgl-pax system:

```
Traceback (most recent call last):
   0 File "unknown"
       In sb-vm::call-symbol
     Args ()
   1 File "/app/src/package-variance-fix.lisp"
       In (lambda (ultralisp/package-variance-fix::compile-function)   :in   asdf/component:around-compile-ho…
     Args (#<function (lambda (&rest asdf/lisp-action::flags)
             :in
             asdf/lisp-action:perform-lisp-compilation) {100D3ECA2B}>)
   2 File "/app/src/package-variance-fix.lisp"
       In (lambda (ultralisp/package-variance-fix::compile-function)   :in   asdf/component:around-compile-ho…
     Args (#<function (lambda (&rest asdf/lisp-action::flags)
             :in
             asdf/lisp-action:perform-lisp-compilation) {100D3ECA2B}>)
   3 File "/app/src/package-variance-fix.lisp"
       In (lambda (ultralisp/package-variance-fix::compile-function)   :in   asdf/component:around-compile-ho…
     Args (#<function (lambda (&rest asdf/lisp-action::flags)
             :in
             asdf/lisp-action:perform-lisp-compilation) {100D3ECA2B}>)
   4 File "/root/.roswell/lisp/asdf/3.3.4.13/asdf.lisp", line 12286
       In asdf/lisp-action:perform-lisp-compilation
     Args (#<asdf/lisp-action:compile-op > #<asdf/lisp-action:cl-source-file "mgl-pax-bootstrap" "src/bootstrap/" "package">)
   5 File "/app/.qlot/setup.lisp"
       In (sb-pcl::emf asdf/action:perform)
     Args (#<unused argument> #<unused argument> #<asdf/lisp-action:compile-op > #<asdf/lisp-action:cl-source-file "mgl-pax-bootstrap" "src/bootstrap/" "package">)
   6 File "/root/.roswell/lisp/asdf/3.3.4.13/asdf.lisp"
       In (lambda () :in asdf/action:call-while-visiting-action)
     Args ()
   7 File "/root/.roswell/lisp/asdf/3.3.4.13/asdf.lisp"
       In (:method asdf/action:perform-with-restarts :around (t t))
     Args (#<asdf/lisp-action:compile-op > #<asdf/lisp-action:cl-source-file "mgl-pax-bootstrap" "src/bootstrap/" "package">)
   8 File "/root/.roswell/lisp/asdf/3.3.4.13/asdf.lisp"
       In (:method asdf/plan:perform-plan (t))
     Args (#<asdf/plan:sequential-plan {1011FCFAF3}>)
   9 File "unknown"
       In (flet sb-c::with-it :in sb-c::%with-compilation-unit)
     Args ()
Condition type-error: The value
                        "mgl-pax.asdf:compile-pax"
                      is not of type
                        (or function symbol)
```

**Comment by svetlyak40wt** [comment]
Try to reproduce this problem compiling your system in clean environment (without fasl files) with `(declaim (optimize (debug 3) (safety 3) (speed 1) (space 1))`.

**Comment by rabbibotton** [comment]
How do I see these errors on your site as they do not appear at all. My project builds clean, it looks like you are compiling example files. Regardless it is not using recent builds. That commit 9f360254a38078bbc6d9204817cff92fe002ddbf is from over a year ago.

**Comment by rabbibotton** [comment]
I tried to remove CLOG from ultralisp so I could put it back and it load latest version and just getting "internal error" on ultraslip

**Comment by svetlyak40wt** [comment]
> That commit 9f360254a38078bbc6d9204817cff92fe002ddbf is from over a year ago.

Correct. Commit 9f360254a38078bbc6d9204817cff92fe002ddbf is the last when successful check (and build) was made.

> Regardless it is not using recent builds.

Incorrect. Ultralisp uses the latest commit when checking the software. It does is not update field "Last seen commit" unless it is able to build a new version of the package.

> My project builds clean, it looks like you are compiling example files.

This is probably correct. Ultralisp tries to find and load all `asd` files including files in subdirectories. If you wish to exclude some directories from build, you have to specify them manually like this:

<img width="1042" alt="Screenshot 2024-02-02 at 16 47 59" src="https://github.com/ultralisp/ultralisp/assets/24827/7b592a0b-f732-4692-84a3-9c82113d061f">

**Comment by svetlyak40wt** [comment]
By the way, I've noticed the commited binary exe file here https://github.com/rabbibotton/clog/tree/main/clogframe.

It would be nice to remove it from the repository or to make a separate repository for this file because of these two reasons.

- Content of the whole repository is packaged and will be downloaded by all CLOG users. This binary file make it bigger.
- Ultralisp rebuild package on every commit (in case if there is no any error) and keeps every version. Storage costs me money :( For frequently changed repositories this can become a problem.

**Comment by rabbibotton** [comment]
Ok, I will work on moving it cloggframe.exe out. Is there a way you can add back CLOG so I can try excluding the sample DIRs to see if that solves the issue. (I tried on two machines fresh builds no issues at all)

**Comment by svetlyak40wt** [comment]
Hm, I see CLOG and it's source. Probably there is some cached state on the serverside. Could you please logout and login again to check it?

I have another [complain](https://fosstodon.org/@fosskers@emacs.ch/111859331556083836) on source deletion, but didn't investigate it yet.

**Comment by rabbibotton** [comment]
logged in and out same issue.

![image](https://github.com/ultralisp/ultralisp/assets/11616789/d121246f-9711-4245-809c-02800dd23768)

**Comment by svetlyak40wt** [comment]
Then this popup is opened? What did you click before?

**Comment by rabbibotton** [comment]
Just entered the source and tabbed to branch which does not show any branches

**Comment by svetlyak40wt** [comment]
Did you remove the source and added it again before tabbing to branch?

**Comment by rabbibotton** [comment]
I did every combo. Is it possible for you to add back the source as I can't save it since I cant add the main branch

**Comment by rabbibotton** [comment]
How would I see if errors still there?

All that I see is 

![image](https://github.com/ultralisp/ultralisp/assets/11616789/5e07221a-99b5-43f0-a25e-b0c5bc1b77a9)

**Comment by svetlyak40wt** [comment]
You need to cancel the editing. Actually, the new version of your project already included into the latest Ultralisp version.

Pay attention, right now Ultralisp has a bug and projects update could stuck: https://github.com/ultralisp/ultralisp/issues/247
I'm fixing this bug right now.

**Comment by rabbibotton** [comment]
Great thanks!
