### ISSUE TITLE
Manual pause and manual update

### ISSUE THREAD

**Issue by rabbibotton** [ultralisp/ultralisp#256]
Because I work on multiple platforms at same time I constantly push creating many updates to UltraLisp. I know there is a throttle in place but it would be better in cases of my to have more manual control instead so that I can manually update when an update is ready for wider distribution with UltraLisp and ways to work around the throttle if even an immediate update was needed.

I propose to add a button on a project to "pause" automatic check of git and a way to manually (and subvert  throttle) restore that default behavior with an immediate update of the check of git. A simple - pause github check on and off would do the trick.

**Comment by svetlyak40wt** [comment]
Right now there is only one way to control release time at Ultralisp – to point it to a release branch and then merge to this branch from your "develop" branch when you feel it is a time for a new release.

Personally I am use another flow – I use feature branches and when I merge a feature branch into the "master", then an update happens at Ultralisp.

There is another approach – not available at Ultralisp yet, but supported by a Quicklisp – to use tags with version numbers. Probably this will be implemented and if you are interested, you can subscribe on corresponding issue:

https://github.com/ultralisp/ultralisp/issues/194

**Comment by rabbibotton** [comment]
subscribed that would work also, as long as only did a release on their presence if I turn on that feature. Just trying to save you the disk space :).
