### ISSUE TITLE
CLOG Disabled - Causes every user to revert to quicklisp version from year ago

### ISSUE THREAD

**Issue by rabbibotton** [ultralisp/ultralisp#257]
Removed projects:
    rabbibotton-clog-20240401015034
==================================================
472,329 bytes in 0.58 seconds (799.67KB/sec)
==================================================
535,118 bytes in 0.57 seconds (924.25KB/sec)
WARNING: "rabbibotton-clog" is not available in #<DIST ultralisp 20240401205000>

=>NIL

The results is every user that is using my one click version of CLOG reverted back to QuickLisp version

1. Why was it disabled and removed?
2. If there was a reason is it possible that the last version remains present in UltraLisp?

**Comment by rabbibotton** [comment]
I see it re-enabled I assume after last push.

So I guess the feature I would say I am requesting is that assuming a build failed was the cause the last known good build stayed available instead of project disabling.

**Comment by rabbibotton** [comment]
This weeks CLOG's master class I mention supporting UltraLisp

https://www.youtube.com/watch?v=TaTEMi4zw04

**Comment by svetlyak40wt** [comment]
Cool! Thank you!

**Comment by svetlyak40wt** [comment]
I've created a new issue about leaving a previous version of a library in a dist in case of an error:

https://github.com/ultralisp/ultralisp/issues/258
