### ISSUE TITLE
CLOG stuck on Waiting in the queue. Position: 1820.

### ISSUE THREAD

**Issue by rabbibotton** [ultralisp/ultralisp#259]
My project change not being picked up, I just checked in a bunch of new changes to git and not seeing it pick up the change and even when manually doing "check" it does not do the check and pick up the changes and remains "position 1820"

**Comment by svetlyak40wt** [comment]
Yeah. Here I've described the problem:

https://github.com/ultralisp/ultralisp/issues/260

I've already made a few attempts to fix it, but still without a success.
Please, track the issue #260
