### ISSUE TITLE
Update version of SBCL used to build projects in Build Queue

### ISSUE THREAD

**Issue by fosskers** [ultralisp/ultralisp#271]
I was casually checking the version of `trial` available in Ultralisp, and noticed that its build is failing. The cause seems to be:

```
Condition LOAD-SYSTEM-DEFINITION-ERROR: Error while trying to load definition for system trial from pathname /tmp/checker/Shirakumo-trial/trial.asd: SBCL 2.1.3 is too old for this program (version 2.2 or later is required).
```

I assume that this means a rather old version of SBCL (from 2021) is used in the build queue. Is that the case?

**Comment by svetlyak40wt** [comment]
You are correct, SBCL 2.1.3 still used for Ultralisp.

**Comment by svetlyak40wt** [comment]
Finally, I've upgraded SBCL to the latest 2.4.6 version!

Trial release was included into the latest Ultralisp dist.

**Comment by fosskers** [comment]
Thank you!
