### ISSUE TITLE
Group Ultralisp projects by source or author

### ISSUE THREAD

**Issue by Hexstream** [ultralisp/ultralisp#31]
It would be really great if for example https://ultralisp.org/projects/Hexstream/its linked to https://ultralisp.org/projects/Hexstream or https://ultralisp.org/projects/Hexstream/ which would show all my projects in Ultralisp, and if there was a way of showing all projects for which the [:author is "Jean-Philippe Paradis" (ignoring email address) in the .asd file](https://github.com/Hexstream/its/blob/master/its.asd#L3) (regardless of source).

(Sorry for using myself as an example. ;P)

**Comment by svetlyak40wt** [comment]
Doing https://ultralisp.org/projects/Hexstream/ URLs is easy, but searching by author's name will be a little bit harder and will require to change `quickdist` library, to extract this information.

I think these improvements should be separated into two issues.

**Comment by svetlyak40wt** [comment]
Done!

For example: https://ultralisp.org/projects/rigetti

**Comment by Hexstream** [comment]
Tremendous! Thank you.

Also consider redirecting URLs like `https://ultralisp.org/projects/rigetti/` to `https://ultralisp.org/projects/rigetti`, this is so that someone who browses `https://ultralisp.org/projects/rigetti/qvm` and then manually hacks up the URL down to `https://ultralisp.org/projects/rigetti/` gets to the right place instead of a 404.

**Comment by svetlyak40wt** [comment]
Ok
