### ISSUE TITLE
Link to Ultralisp on GitHub from Ultralisp homepage

### ISSUE THREAD

**Issue by Hexstream** [ultralisp/ultralisp#33]
https://ultralisp.org/ should definitely link to https://github.com/ultralisp/ultralisp.

Relatedly, the "Leave feedback" link is not user-friendly because it links to https://github.com/ultralisp/ultralisp/issues/new which requires one to login. It would be better if that linked to https://github.com/ultralisp/ultralisp/issues instead.

**Comment by svetlyak40wt** [comment]
> https://ultralisp.org/ should definitely link to https://github.com/ultralisp/ultralisp

Where would you place this link?

**Comment by Hexstream** [comment]
Anywhere would be better than nowhere.

Maybe a "See on GitHub" link besides "Leave feedback"...

Or maybe even just replace "Leave feedback" with the "See on GitHub" link.

**Comment by svetlyak40wt** [comment]
Done!

**Comment by Hexstream** [comment]
Yeah, I had thought about the trendy ribbon thing. Nice. :)
