### ISSUE TITLE
Patreon?

### ISSUE THREAD

**Issue by Hexstream** [ultralisp/ultralisp#38]
I see that you now accept donations via Liberapay.

I reviewed them a bit, and honestly they seem to be a bit of a [struggling service](https://twitter.com/liberapay/status/1098172939713810433). (It also seems that donators have to do a lot of micromanagement to continue donating, which seems worrying.)

Patreon seems like a more hopeful service, they are the biggest funding platform of their kind and can fund a broader set of project kinds. Here are a few successful programming projects I've found on there:

[Vue.js ($17,621/month)](https://www.patreon.com/evanyou), [Team Cemu ($6,047/month)](https://www.patreon.com/cemu), [gelbooru ($528/month)](https://www.patreon.com/gelbooru).

Your [target](https://en.liberapay.com/Ultralisp.org/) of 100$/week seems much easier to reach on Patreon than Liberapay.
[Liberapay themselves](https://liberapay.com/Liberapay/) are making 175.73$ USD a week on their own platform...

There are a few Common Lispers on Patreon, no great successes so far but I think we could eventually reach a critical mass on there, if we "standardize" on Patreon a bit.

So, I think you should consider adding Patreon as a funding option.

**Comment by svetlyak40wt** [comment]
Great idea! I'll read more about Patreon and try to add this as an option.

**Comment by svetlyak40wt** [comment]
Done!
