### ISSUE TITLE
Tried to sign up, afraid of having my private repos be seen

### ISSUE THREAD

**Issue by guicho271828** [ultralisp/ultralisp#39]
Perhaps this should be unfair to complain about it here but the github OAuth token is scary, it tells me that Ultralisp app may read the private repository metadata as well as ask the corporate organization account to reveal its metadata. I don't want either to happen.

**Comment by Hexstream** [comment]
I don't remember the OAuth flow, but when I go in my OAuth settings for the Ultralisp app I see that I was able to grant access to the StreamLisp organization and refuse access to my 2 "pseudo-organizations". I hope the private repos issue can be fixed, that's certainly concerning.

Also see #16, which is vaguely related.

**Comment by Hexstream** [comment]
Ok, this is actually very easy to solve on your end.

https://help.github.com/en/articles/enabling-oauth-app-access-restrictions-for-your-organization

I did this for the StreamLisp organization right now, works like a charm.
(I was misremembering when I thought I had granted access, I had just not revoked access.)

**Comment by svetlyak40wt** [comment]
Interesting. I though, I've fixed this issue with 10ce3a69d94ded05087ff57ed4cc19be22dbc087 commit.

**Comment by svetlyak40wt** [comment]
@guicho271828 are you sure that Ultralisp asks you for access to the private repositories of your organizations?

Could be please add a screenshot of the GitHub page where it asks you to authorize Ultralisp.org?

**Comment by guicho271828** [comment]
> screenshot
Will do.

**Comment by Hexstream** [comment]
I haven't wrapped my head around this, but here's [some information about OAuth scopes](https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/), for reference.

**Comment by guicho271828** [comment]
![Screenshot from 2019-03-29 00-29-48](https://user-images.githubusercontent.com/1321968/55170693-572f5f00-51ba-11e9-92b1-a5f4dd7bf875.png)
![Screenshot from 2019-03-29 00-31-51](https://user-images.githubusercontent.com/1321968/55170702-5991b900-51ba-11e9-90a9-980928b84225.png)
![Screenshot from 2019-03-29 00-33-44](https://user-images.githubusercontent.com/1321968/55170716-5dbdd680-51ba-11e9-9082-07a7b24df081.png)

**Comment by guicho271828** [comment]
Re: 10ce3a6 , I think you need to set `public_repo` flag set

**Comment by guicho271828** [comment]
From my org list, you would see now that if I do something wrong then I have the possibility to be chased down to the end of the hell :)

**Comment by svetlyak40wt** [comment]
I've deployed a fix!

@guicho271828 thank you for the pull!

![2019-03-30_01-31-23](https://user-images.githubusercontent.com/24827/55265987-bb6e2380-528b-11e9-86e2-9f94e5dfa75c.png)
