### ISSUE TITLE
Dedicated Ultralisp chatroom

### ISSUE THREAD

**Issue by Hexstream** [ultralisp/ultralisp#40]
I think it would be worth it to create a dedicated chatroom for Ultralisp at https://gitter.im/40ants/ultralisp and link it from the homepage. After all, Ultralisp is a particularly important project that people might want to tune into.

This would be a great complement to the [more generic room](https://gitter.im/40ants/team).

**Comment by Hexstream** [comment]
Or maybe https://gitter.im/ultralisp/ultralisp, I'm not yet familiar with gitter so I'm not sure if that would be better or not...

**Comment by svetlyak40wt** [comment]
I've created a https://gitter.im/ultralisp-org/community

**Comment by svetlyak40wt** [comment]
For some reason Gitter prevented me from taking the name https://gitter.im/ultralisp

**Comment by Hexstream** [comment]
Ah, that's unfortunate. A squatter, perhaps?

I thought that GitHub and gitter were tightly linked such that you controlling the Ultralisp organization guaranteed that you could create https://gitter.im/ultralisp/ultralisp... seems not. :(

I guess we'll have to make do with that alternative name...

**Comment by svetlyak40wt** [comment]
I've written an email to their support, maybe it will be possible to rename the url.

**Comment by Hexstream** [comment]
Actually, have you verified that you have allowed gitter to access the Ultralisp organization?

**Comment by Hexstream** [comment]
Use the `do you want to start a community for one of your github projects?` in `Add a room` on gitter, if that's not already what you were trying to do...
