### ISSUE TITLE
Create a page where all my projects are listed

### ISSUE THREAD

**Issue by svetlyak40wt** [ultralisp/ultralisp#44]
RIght now login menu has a link to https://ultralisp.org/my/projects page, but it does not exist.

This should be fixed and list like https://ultralisp.org/projects/40ants should be rendered instead of 404 page.

**Comment by svetlyak40wt** [comment]
Now this issue is fixed: https://github.com/ultralisp/ultralisp/commit/b252e47d4d8532f2b119b97b120982d7efeacf05. The page /my/projects shows all projects where I'm the moderator.

**Comment by Hexstream** [comment]
Great feature, thanks!
