### ISSUE TITLE
Slight incompatibility with installed systems database

### ISSUE THREAD

**Issue by Hexstream** [ultralisp/ultralisp#51]
Hello,

I've decided to install the Ultralisp dist and remove the Quicklisp dist. :)

One issue I've come across is that some systems like `quicklisp-slime-helper` and my own `clhs` ASDF wrapper rely on files with names like
`quicklisp/dists/[dist]/installed/systems/[system].txt` whereas, for some reason, the ultralisp dist provides files named
`quicklisp/dists/[dist]/installed/systems/[system].asd.txt` instead.
Note the extra `.asd` part.

For now, I've simply edited the `quicklisp/slime-helper.el` and `quicklisp/clhs-use-local.el` files to expect the extra `.asd` part in the filenames. Maybe consider removing the extra `.asd` part in filenames if that was an accidental incompatibility.

Sorry for this hastily written bug report, let me know if you need more information.

**Comment by svetlyak40wt** [comment]
That is interesting. Probably should be fixed somewhere in the https://github.com/ultralisp/quickdist

**Comment by svetlyak40wt** [comment]
I've investigated this issue and found the difference in systems.txt generated by quickdist and quicklisp.

There is a column system-file and quicklisp's metadata contains just a filename without a folder and extension:

```
# project system-file system-name [dependency1..dependencyN]
…
sly slynk slynk/arglists slynk
...
```

But metadata generated by quickdist contains a full (relative) path to asd file:

```
# project system-file system-name [dependency1..dependencyN]
…
joaotavora-sly slynk/slynk.asd slynk/arglists slynk
...
```

This should be fixed in Quickdist.

**Comment by svetlyak40wt** [comment]
This bug was fixed in https://github.com/ultralisp/ultralisp/commit/66b90c9b3fbcf57701ecbe0e62cdd143322a23a0 commit.
