### ISSUE TITLE
Wrong title on user projects page

### ISSUE THREAD

**Issue by Hexstream** [ultralisp/ultralisp#54]
The document title I'm getting at https://ultralisp.org/projects/Hexstream is basically random and completely wrong. One example was "soemraws/pack – Python struct hack in Common Lisp written by Death". Refreshing the page gives other similarly wrong document titles. (Sometimes the same wrong title will stick around for a bit.)

**Comment by svetlyak40wt** [comment]
That is because weblocks is a single page application and each widget should change page title if it is required.

**Comment by svetlyak40wt** [comment]
Fixed in a commit https://github.com/ultralisp/ultralisp/commit/c5437b637309ea53cfcf07987e132394fdfbcb95

**Comment by Hexstream** [comment]
> That is because weblocks is a single page application and each widget should change page title if it is required.

That's... unorthodox. Anyway, thanks for the fix.
