### ISSUE TITLE
Why does ultralisp require access to my github org?

### ISSUE THREAD

**Issue by notmgsk** [ultralisp/ultralisp#69]
![Screen Shot 2020-02-28 at 5 36 46 PM](https://user-images.githubusercontent.com/16821631/75598522-0b7fd800-5a51-11ea-9c7c-208d7070c05a.png)

**Comment by Hexstream** [comment]
Wasn't it, like, you can explicitly grant the app access to some of your orgs if you want to, but you don't have to?

I have not granted Ultralisp to any of my orgs, because all my ready-to-use projects are under my main account, not orgs.

**Comment by notmgsk** [comment]
Honestly I'm not sure, and it's not clear from the page (IMO):
<img width="525" alt="Screen Shot 2020-02-28 at 6 18 09 PM" src="https://user-images.githubusercontent.com/16821631/75599153-c2328700-5a56-11ea-9e4a-87aa81c510d0.png">

**Comment by Hexstream** [comment]
The GitHub UI could be clearer, but here's what it would look like if you did grant access: https://github.com/ultralisp/ultralisp/issues/66#issuecomment-589998321

So, no green checkmark means the app won't have any access to your orgs, I believe.

**Comment by notmgsk** [comment]
Ah. Thanks for clarifying.
