### ISSUE TITLE
loading cl-json was failed because somebody added https://github.com/kennytilton/qooxlisp

### ISSUE THREAD

**Issue by svetlyak40wt** [ultralisp/ultralisp#70]
Project https://github.com/kennytilton/qooxlisp brings old version of the cl-json inside.

**Comment by svetlyak40wt** [comment]
Correct version is here: https://github.com/hankhero/cl-json/blob/master/cl-json.asd

**Comment by mmontone** [comment]
Yes. I cannot load my projects because of this. What to do about it?

**Comment by svetlyak40wt** [comment]
We have to add an interface to blacklist some asd files inside the project. Now I'm working on a new interface for projects. And after that it will be possible to implement this feature.

@mmontone subscribe on this pull https://github.com/ultralisp/ultralisp/pull/87

**Comment by C-Entropy** [comment]
Came into similar case, [web-toolkit](https://github.com/xh4/web-toolkit/) brings bunch of old version packages. Is there any solution to this now?

**Comment by svetlyak40wt** [comment]
This should be fixed by:

- https://github.com/ultralisp/ultralisp/pull/121
- and https://github.com/ultralisp/ultralisp/pull/123

But seems, blacklisting does not work as expected because I see "kennytilton/qooxlisp" was disabled. It's `vendor` directory should be ignored instead:

<img width="829" alt="Screen Shot 2021-03-16 at 16 20 30" src="https://user-images.githubusercontent.com/24827/111315770-bfabcb00-8673-11eb-826c-da447343637b.png">

The same problem is with the https://ultralisp.org/projects/xh4/web-toolkit

Loading of the correct `cl-json` version is fixed now:

```
* (ql-dist:all-dists)
(#<QL-DIST:DIST quicklisp 2021-02-28> #<QL-DIST:DIST ultralisp 20210316062004>)
* (ql:where-is-system :cl-json)
#P"/private/tmp/.qlot/dists/ultralisp/software/hankhero-cl-json-20200326183916/"
```

A problem with disabled `qooxlisp` and `web-toolkit` I'll fix in another issue: https://github.com/ultralisp/ultralisp/issues/124
