### ISSUE TITLE
Find a  way to solve conflicts between ASDF systems

### ISSUE THREAD

**Issue by svetlyak40wt** [ultralisp/ultralisp#73]
System "str" conflicts because it is defined in two projects.

Currently, [thodg/str](https://ultralisp.org/projects/thodg/str) is installed instead of [vindarel/cl-str](https://ultralisp.org/projects/vindarel/cl-str). The latter is available from Quicklisp.

We need to add some way to choose which system to install. Probable something like custom distributions can be introduced, when anyone can choose libraries he wants and they will be included in a separate quicklisp distribution.

**Comment by svetlyak40wt** [comment]
@vindarel do you have an idea how to solve this problem?

**Comment by vindarel** [comment]
Other than preventing to add a system with a name that already exists, I don't see. `thodg/str` would have been rejected. Of course it is not the best, and this would prevent systems that rely on `thodg/str` to be added too :/

**Comment by Hexstream** [comment]
> Probable something like custom distributions can be introduced, when anyone can choose libraries he wants and they will be included in a separate quicklisp distribution.

That would be the best feature ever! I've always wanted to have an HexstreamSoft dist, but I don't want to setup the infrastructure for it.

In my view, anyone with 3 or more libraries should ideally publish their own dist...
