### ISSUE TITLE
Custom dists

### ISSUE THREAD

**Issue by Hexstream** [ultralisp/ultralisp#77]
As you said in #73:

> Probable something like custom distributions can be introduced, when anyone can choose libraries he wants and they will be included in a separate quicklisp distribution.

That would be the best feature ever!

**Comment by Hexstream** [comment]
I'd really love to have an HexstreamSoft Ultralisp dist for all my projects (a "stable" dist for latest releases only, and possibly another for master branch) plus their dependencies, so I'm putting all the weight I'm entitled to as [Grand Supporter](https://www.patreon.com/ultralisp) towards the completion of this issue. :)

[This would be a dream come true!](https://twitter.com/HexstreamSoft/status/706235734357893120)

PS: It seems the [Ultralisp sponsors page](https://ultralisp.org/sponsors) has not yet been updated. ;)

**Comment by svetlyak40wt** [comment]
I'd like to start working on this feature soon.

Could you elaborate on what is the "stable" dist and what is the best way to learn about what is considered "stable" and distinguish it from the "latest".

Still not sure if I want to introduce such complication like discovering stable releases.

**Comment by Hexstream** [comment]
Currently, the Quicklisp dist only ever [pulls](https://github.com/quicklisp/quicklisp-projects/blob/master/projects/definitions-systems/source.txt) from [my latest official tarballs](https://www.hexstreamsoft.com/libraries/releases/latest-versions/) such as `https://tarballs.hexstreamsoft.com/libraries/latest/definitions-systems_latest.tar.gz`. This is a great idea for the Quicklisp dist since it updates only once a month. I tend to be a bit more careful about updating my official releases than my master branch. I definitely DO NOT want some random bug from my master branch to end up in a Quicklisp dist and having to live with that for a month, hence pulling only from official releases.

In contrast, the Ultralisp dist only ever pulls from my master branches. This is a good idea since Ultralisp updates instantly, so even if a bad commit ends up on my master branch I can quickly fix it and Ultralisp updates immediately.

If anyone could easily create their own custom curated Ultralisp dist, I would probably elect to have 2 of them: A "stable" one that contains all my official releases (like in Quicklisp) plus their dependencies, and an "unstable" one that contains all my master branches (like in Ultralisp) plus their dependencies. This way, people would have a choice of which model they prefer to use, more conservative or more progressive. If they find a bug they could also compare the 2 versions to see if this a recently introduced regression.

**Comment by svetlyak40wt** [comment]
Oh, this seems like a big "epic" which should be to the separate stories:

0. User can create one or more custom distributions.
1. The user can include any project into his custom distribution.
2. The tar archives downloaded via HTTP can be used as the source.
3. [Optional] For GitHub source a tag or branch can be configured.
4. A project with a custom name can be added.
5. A custom distribution can be configured to implicitly include all dependencies from the "common" distribution.

When this will be done, you will have the ability to:

0. Create two distributions: "stable" and "latest".
1. Create the project: hexstream/definitions-systems which will fetch from GitHub's master branch.
2. And hexstream/definitions-systems-stable which will fetch from GitHub's "lastest" tag.
3. Include the hexstream/definitions-systems into "lastest" distribution.
4. Include the hexstream/definitions-systems-stable into the "stable" distribution.

Did I miss something?

**Comment by Hexstream** [comment]
Almost perfect!

But `hexstream/definitions-systems-stable` is extremely ugly. I want the project to be called `hexstream/definitions-systems` in both the `stable` and `latest` dists, with the former pulling from official releases and the latter pulling from master branches.

**Comment by svetlyak40wt** [comment]
@Hexstream these names should be different for Ultralisp to distinguish between different sources. In both cases the system name will be the same `definitions-systems`.

We can make different sources for a single project, but it will be hard to make an interface to setup rules which of the sources is bound to which distribution.

In this case we'll have to have "one-to-many" links between:

* projects and sources;
* sources and distributions.

![different-source](https://user-images.githubusercontent.com/24827/91888365-d91b9580-ec94-11ea-9289-642749a4cfd1.png)

I'd prefer to implement a simpler solution where projects are separate because in this case, we need "one-to-many" links only between projects and distributions:

![separate-projects](https://user-images.githubusercontent.com/24827/91888382-e0db3a00-ec94-11ea-9811-4e7f94cc986a.png)

In most cases, people want just have a single project with the latest code available.

**Comment by Hexstream** [comment]
I could live with just a releases-only or master-branches-only dist as a first step, but I think if you use the right conceptual model, then it will be just as easy to support infinite dists. I think the key is to ensure that the [closure property](https://en.wikipedia.org/wiki/Closure_(mathematics)) holds for dists.

At the core of the paradigm, I think each custom dist should have (potentially) exactly the same standing as the "god dist" (the default Ultralisp dist). It should not matter if a project is represented in just one dist or multiple dists, and if it's pulled from one source or multiple sources across dists (but always from one source per project per dist). dists should always be independent of each other except when one explicitly falls back to another one (such as my dists fetching dependencies from the default Ultralisp dist as needed). It should be possible to use a custom dist and not use the default Ultralisp dist at all. It should even be (at least technically) possible for a custom dist to replicate/replace the default Ultralisp dist, possibly with amendments (although I'm not sure why someone would want to do this, but it's useful to plan for).

For instance, both my `stable` and `latest` dists would be completely independent of each other, with each one of them having all of my projects under the expected name, such as `hexstream/definitions-systems`. As a first step, I don't think it would be required that these 2 dists be compatible, that is to say, you would need to choose either `stable` or `latest`. But Ultralisp really doesn't even need to realize that these 2 dists have essentially the same projects, just pulled from different sources. Ultralisp should just treat different sources as completely unrelated projects that might just happen to have the same name (in different dists) and mostly the same contents.

Of course, Ultralisp could and should cache projects from the same source across different dists...

Let me know if you can make sense of what I'm saying, it's important to get the basic conceptual model right so we don't need to use a sledge hammer to fix the problems later..

PS: I appreciate the nice presentation! How did you make these graphs?

**Comment by svetlyak40wt** [comment]
I'll make an MVP of this feature and it will available only to you under the "feature flag".

Graphs were made with Diagrams app. I've installed it today using https://setapp.com

**Comment by Hexstream** [comment]
Looking forward to it!

Also, it doesn't necessarily have to be in a first version, but I would ideally want to host at least my `stable` dist at `dist.hexstreamsoft.com` or something. Just a manual export feature would be enough, at first.

**Comment by adlai** [comment]
Why is this still open?

**Comment by svetlyak40wt** [comment]
@adlai thank you! I forgot to close the issue.
