### ISSUE TITLE
Lack of canonical-dist-url: in distinfo.txt causes quicklisp bundle errors

### ISSUE THREAD

**Issue by jesseoff** [ultralisp/ultralisp#81]
When attempting to create any quicklisp bundle and ultralisp is enabled, quicklisp signals an error.

I have a pull request in quicklisp-client to fix this: https://github.com/quicklisp/quicklisp-client/pull/202  But it may be simpler to just have ultralisp define this field.  It doesn't really matter if its correct or not, its just used to create a metadata file to go along with the generated bundle.

**Comment by fukamachi** [comment]
Possible solution: https://github.com/fukamachi/quickdist/commit/a427f5d66e25063873240d1ab65f3271fecdf5ca

**Comment by svetlyak40wt** [comment]
I've updated quickdist used by Ultralisp and latest dists are having canonical-distinfo-url!

**Comment by fukamachi** [comment]
Good to hear, thank you!
