### ISSUE TITLE
Not finding project

### ISSUE THREAD

**Issue by mohindertalafuse** [ultralisp/ultralisp#82]
I have a Common Lisp repo to add, but it has some HTML and SH in it. However, it is still listed as a Common Lisp repository. When I log on to UltraLisp, it just goes to loading wheel and never finds my project...

**Comment by svetlyak40wt** [comment]
Please, give a link to the repository.

**Comment by mohindertalafuse** [comment]
Thanks, here it is:
—click this text <http://github.com/mohindertalafuse/lispmath>--

**Comment by mohindertalafuse** [comment]
Sorry, it is <a href='http://github.com/mohindertalafuse/lispmath'>here</a>.

**Comment by svetlyak40wt** [comment]
Ultralisp shows only repositories for which GitHub returns that there is Common Lisp code. Here is this part in the Ultralisp's code: https://github.com/ultralisp/ultralisp/blob/master/src/github/widgets/repositories.lisp#L89-L114

Probably GitHub wasn't aware that there is Common Lisp in the repository. But now it reports it is 100% Common Lisp:

<img width="547" alt="Screenshot 2020-08-28 at 20 14 19" src="https://user-images.githubusercontent.com/24827/91594838-36e57000-e96b-11ea-8ac0-7d40a985453e.png">

Please, try again to add your project.

**Comment by svetlyak40wt** [comment]
Also, I've created this separate issue https://github.com/ultralisp/ultralisp/issues/83  to fix caching issue.

**Comment by mohindertalafuse** [comment]
Thanks so much! Although, how do I actually *add* the project?

**Comment by svetlyak40wt** [comment]
Yes, I've seen the .gitattributes in the repository. That is why I suggested to try again.

If this issue will hit other users, then I'll add an ability to list all repositories instead of the only CL.

**Comment by mohindertalafuse** [comment]
Thanks!
