### ISSUE TITLE
Please remove Hexstream's access to Ultralisp and all repositories

### ISSUE THREAD

**Issue by phoe** [ultralisp/ultralisp#90]
Hello,

I would like to bring your attention to the behavior of @Hexstream that, I assume, might be already well-known to you. 

I regret to inform you that his most recent [GitHub conversation](https://github.com/cl-library-docs/common-lisp-libraries/issues/3), in which I have once more attempted to convince him to change his behavior and publish actual data that shows his real amount and quality of involvement in the Common Lisp community, [I have been announced the main threat to the *whole* Common Lisp community](https://twitter.com/HexstreamSoft/status/1331080126860234752), [declared impossible to directly and indirectly fund in an ethical manner](https://twitter.com/HexstreamSoft/status/1331102289386409985), and then [proclaimed that require immediate medical attention of psychiatric nature](https://twitter.com/HexstreamSoft/status/1331127527977463809).

Hexstream has been ranting on [Twitter](https://twitter.com/HexstreamSoft/) and derailing many [[1]](https://github.com/quickdocs/quickdocs/issues/46) various[[2]](https://github.com/vindarel/lisp-maintainers/pull/1) GitHub[[3]](https://github.com/Hexstream/fakenil/issues/2) discussions[[4]](https://github.com/Hexstream/common-lispers.hexstreamsoft.com/issues/14) at least since 2015. In this time, he has not been stopped by anyone or anything, and this lack of action caused concrete and direct harm to the Common Lisp community.

* He has repeatedly defamed various honored and respected members of the Common Lisp community, including [Rainer Joswig](https://twitter.com/hexstreamsoft/status/1118934532273704960), [Michael Fiano](https://twitter.com/HexstreamSoft/status/1267093005271433218), [Daniel Kochmański](https://twitter.com/HexstreamSoft/status/1171975874276679680), [Stas Boukarev](https://twitter.com/HexstreamSoft/status/1043671920649142272), [Zach Beane](https://twitter.com/HexstreamSoft/status/1054828493467541510), and me. This list is not exhaustive and includes various other Common Lisp programmers on GitHub who have not approved of his behavior.
* He has published a public service announcement detailing his delusion about Zach Beane being a sociopath and a member of the Common Lisp Mafia, and made it available under a custom-purchased domain, https://xach.exposed.
* He fraudulently claims that he is a Common Lisp expert, while [a simple glance at his "extensive contributions"](https://gist.github.com/phoe/ccba343687dc21e3a71d0dc6db68c96e) reveals that they are void, baseless, lack any concrete merit, and completely do not suit the image that he tries to create around himself, which is one of a Common Lisp expert with five years of commercial experience and fifteen years of general Lisp experience.
* He published an online list of Lisp programmers from which he refuses to remove people, because of his made-up policies that he invents and modifies on the spot as appropriate and refuses to consult with anyone.

He is extremely antisocial and abrasive, which further stresses the part of the Common Lisp community that attempts to have fruitful and civil discussion on GitHub.

* He always approaches other people with his arrogant, egocentric point of view, in which his opinion is law, and points of view of others are fully and completely ignorable, and also valid targets for unwinding his aggression.
* Whenever the above arrogance is not respected in any way, he becomes vulgar, aggressive, offensive, obscene, ironic, and derogatory towards his conversation partners.
* When this aggression is pointed out to him and he is pushed to make an answer, he plays the victim card and considers himself to be silenced, censored, and tortured by a so-called "Common Lisp Mafia" that is an invention of his own deluded mind in order to avoid taking responsibility for his actions.
* This behavior of his has been pointed out to him hundreds of times throughout these years, and has not changed, which brings me to the unfortunate but required conclusion, that he is impossible to reason with and must instead be removed from the Common Lisp community by force for the good of our community.
* This kind of behavior directly threatens the healthy future of the Common Lisp community by driving away newcomers to the language, who seek a friendly, inclusive, and non-aggressive environment in which they may learn the language and the programmers.

I can provide more evidence and logs of this behavior on request.

I have written a [blogpost](https://nl.movim.eu/?blog/phoe%40movim.eu/3feaeb8e-0af5-4ddf-b284-5de71ff03804) about this most recent meltdown of his that contains more details and further links.

This kind of behavior has been going on **for years** with multiple members of the Lisp community being targeted. Because of this, it is no longer tolerable in any way. This kind of continuous behavior has been repeated without any hints of change from Hexstream's side require immediate and solid attention in order to protect the Common Lisp community from his influence.

**Therefore, I request immediate revocation of Hexstream's access to the Ultralisp group on GitHub and removal of all of his systems in the Ultralisp dist.** Hexstream's ASDF systems have no non-Hexstream dependents in the current dist, which makes them trivial to remove as a whole.

Such action is highly desired and required for the good of the Common Lisp community, as shown by extensive commentary of my discussion with Hexstream on [Reddit](https://www.reddit.com/r/lisp/comments/jzoimg/please_take_a_second_to_show_support_for_uflaming/), [Freenode IRC](https://irclog.tymoon.eu/freenode/%23lisp?around=1606191018#1606191018), [Lisp Discord](https://discord.com/channels/297478281278652417/297478485000192010/780625634607104011), and [Fediverse](https://functional.cafe/@phoe/105263444756143076).

Those discussions in these places mean that the issue with Hexstream is widely known, my means of dealing with him in the main GitHub issue have been appropriate, and the problem has been noticed and acknowledged by tens of members of the Common Lisp community. These people, I assume, would also enjoy a Common Lisp community that is not based upon the pseudo-"ethics" of verbal violence, vulgarity, pretentious meritlessness, paranoidal conspiracy theories, and absolute lack of respect towards other people.

------------------

A matching removal request has been [submitted to the Quicklisp repository](https://github.com/quicklisp/quicklisp-projects/issues/1941) given the high importance of this issue.

------------------

I am aware that Hexstream [is a current sponsor of Ultralisp](https://ultralisp.org/sponsors), which provides you with a substantial amount of money, but also complicates your relationship with Hexstream. I understand this additional complexity; however, I also urge you to consider the aforelisted evidence that is greatly in favor of no longer enabling years of Hexstream's continuously abusive behavior towards the Common Lisp community.

If required, I will gladly organize a fundraiser in the Common Lisp community and chip in myself in order to keep the costs of running Ultralisp bearable for you.

**Comment by vindarel** [comment]
I don't see the logical step that leads to this. I find this request weird, violent, illegitimate, inappropriate and counter-productive (he can now claim to be censored).

**Comment by phoe** [comment]
> I don't see the logical step that leads to this.

This is to make a very strong point that indulging aggressive and defamatory behavior towards members of the Common Lisp community for five years straight, as listed above, is not acceptable in any way and has direct consequences. Hexstream's merit is non-zero when it comes to source code, but it is also massively shadowed by the obnoxious behavior that he is infamous for in the Common Lisp community.

> (he can now claim to be censored)

The only censorship that is currently happening is the protection of the Common Lisp community against Hexstream's influence and breaking the continuous streak of five years of his constant obnoxious behavior, as listed above.

If he considers this to be censorship, then so be it; I have run out of any more chances to give him and have decided to instead act to protect the Lisp community from continuous aggression and deluded paranoia of Hexstream's making, since he has proven completely unable to contain it on his own.

**Comment by mfiano** [comment]
While I haven't made contact with him in a couple years, I see that he is still targeting myself and others when things don't go his way. I support this request, not because he bothers me, but because it bothers me that the Lisp community is suffering from his volatile behavior.

**Comment by mohe2015** [comment]
Without being involved in this community recently at all I would also vote for removing his access as he violates all Code of Conducts that exist on the planet and I think it's important that an online community follows some rules and is respectful to each other.

**Comment by svetlyak40wt** [comment]
Ultralisp was created to be equally available to everyone.

There will no be any censorship except cases when a person tries to break the service.

**Comment by Hexstream** [comment]
Thank you. [I might be banned from Quicklisp](https://twitter.com/HexstreamSoft/status/1331319164678574084), which would certainly be unfortunate (and perhaps entirely uncalled for), but is much less destabilizing if I still have access to Ultralisp, which is a better service in many ways.

**Comment by tfeb** [comment]
This is mostly a repeat of [my comment in the Quicklisp issue](https://github.com/quicklisp/quicklisp-projects/issues/1941#issuecomment-733708562).

Please don't do this, or at least not because of this issue (or this comment). The CL community has a very long history of difficult and sometimes abusive people, including me.  Hexstream is very clearly one such person.  But the solution to these people is not to attempt to form some cabal to drive them out: the solution is to not engage with them at all – to just walk away. If some difficult person believes that they are being persecuted by some mythical Common Lisp Mafia then when a bunch of Common Lisp people *get together and persecute them* all you are doing is providing them reinforcment.

Instead, well, all these new-fangled things have killfiles: you can block users on GitHub, you can I am sure block people on Twitter, you can ignore people on IRC. Just walk away.

Finally I can again state with some certainty that the Common Lisp Mafia has not, in fact, persecuted this person.  I have had some of my assistants check the files and no such persecution has been authorised and nor are there any immediate plans for any: if persecution has taken place it has not been by members of the CLM or by its representatives.  Indeed, action taken by the CLM against its enemies is usually immediately recognisable: the signatures are, I believe, well-known.

**Comment by Hexstream** [comment]
Thank you, [I endorse your great proposal](https://twitter.com/HexstreamSoft/status/1331693903574159362). [Per my CV](https://cv.hexstream.expert/), my extensive contributions already have a critical mass of positive attention anyway, so it is fine at this point if people who don't understand my value ignore me, which is preferable to a rise of fascism.

**Comment by Hexstream** [comment]
[Phoe backed down, but I'm still blocked from the Quicklisp GitHub.](https://twitter.com/HexstreamSoft/status/1331743501818736646)

**Comment by Hexstream** [comment]
[I've been unblocked from the Quicklisp GitHub!](https://twitter.com/HexstreamSoft/status/1333292483023953921)

@vindarel Profound thanks for your multiple awesome interventions in my favor on this.

(I'm not sure what you mean by your thumbs down reaction on my endorsement of Tim's proposal, however.)
