### ISSUE TITLE
Project shamazmazum/similar-images: check-error

### ISSUE THREAD

**Issue by shamazmazum** [ultralisp/ultralisp#91]
Hi, my project is removed from Ultralisp and I see this error on [project page](https://ultralisp.org/projects/shamazmazum/similar-images):
![20201126_18h33m43s_grim](https://user-images.githubusercontent.com/812069/100413470-7d408d00-3088-11eb-893e-2f6a14584a2f.png)

Can you check what's going on?

**Comment by svetlyak40wt** [comment]
Checking.

**Comment by svetlyak40wt** [comment]
You were punished for the "force push". Ultralisp caches the repository and does `git pull` if there is cached data on the disk.

Now I've cleared the cache and project was updated.

Please, don't do `push --force` anymore :)

**Comment by shamazmazum** [comment]
Yes, it was stupid. I was tired and pushed shit to master and then force-pushed within 5 minutes or so. I know it's a bad practice, didn't thought it's so bad :)

Thanks, I will avoid this in the future.
